import type { CaseState } from "./types";

export const defaultCaseState: CaseState = {
  workspaceName: "",
  workspaceMode: "",
  currentPhaseLabel: "",
  postClosureContinuity: "",
  networkSelfManagementTools: "",
  familyManagedHandoverStatus: "not_started",
  familyManagedHandoverLeadMembershipId: "",
  familyManagedHandoverLeadName: "",
  familyManagedHandoverLeadRole: "",
  familyManagedHandoverActivatedAt: "",
  familyManagedHandoverNotes: "",
  caregiverSummary: "",
  currentWatchpoint: "",
  planStability: 0,
  immediateActionsText: "",
  riskStatement: "",
  safeguardingGoals: "",
  safeguardingScale: 0,
  timelineEntries: [],
  networkMembers: [],
  currentGapsText: "",
  nextNetworkStepsText: "",
  nextNetworkSteps: [],
  currentPlanningPhase: "immediate",
  immediatePlan: {
    heading: "",
    purpose: "",
    status: "Draft",
    actions: "",
    members: "",
    reviewDate: "",
  },
  intermediatePlan: {
    heading: "",
    purpose: "",
    status: "Draft",
    actions: "",
    members: "",
    reviewDate: "",
  },
  longTermPlan: {
    heading: "",
    purpose: "",
    status: "Draft",
    actions: "",
    members: "",
    reviewDate: "",
  },
  rules: [],
  monitoringItems: [],
  fireDrillScenario: "",
  fireDrillDate: "",
  fireDrillParticipants: "",
  fireDrillRecordNotes: "",
  closureAlertNote: "",
  closureAppointments: [],
  closureActionItems: [],
  planAdaptationText: "",
  communicationMitigationText: "",
  urgentCpsContactText: "",
  closureJournalText: "",
  changeLog: [],
};

export function cloneDefaultCaseState(): CaseState {
  return JSON.parse(JSON.stringify(defaultCaseState)) as CaseState;
}
